/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.monster.vista;

import ec.edu.monster.controlador.EurekaControlador;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author chris
 */
public class DepositosVista extends javax.swing.JFrame {

    /**
     * Creates new form DepositosVista
     */
    public DepositosVista() {
        this.setLocationRelativeTo(null);
        initComponents();
        TextPrompt cuenta = new TextPrompt("Número de Cuenta", txtCuenta) ;
        TextPrompt cuentaDestino = new TextPrompt("Número de Cuenta Destino", txtCuentaDestino) ;
        TextPrompt deposito = new TextPrompt("Monto del Depósito", txtDeposito) ;
        
        // Inicializar movimientoCodigos y el ComboBox
        initializeMovimientoCodigos();
        initializeComboBox();  
    }
    private HashMap<String, String> movimientoCodigos;

    private void initializeMovimientoCodigos() {
        movimientoCodigos = new HashMap<>();
        movimientoCodigos.put("Depósito", "003");
        movimientoCodigos.put("Retiro", "004");
        //movimientoCodigos.put("Transferencia 1", "008");
        movimientoCodigos.put("Transferencia", "009");
    }
    
    private void initializeComboBox() {
        for (String descripcion : movimientoCodigos.keySet()) {
            jComboBox1.addItem(descripcion);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        txtDeposito = new javax.swing.JTextField();
        btnDeposito = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtCuentaDestino = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Realizar Depósito");

        txtCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCuenta.setForeground(new java.awt.Color(51, 0, 51));
        txtCuenta.setText("Cuenta Origen");
        txtCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaActionPerformed(evt);
            }
        });

        txtDeposito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDeposito.setForeground(new java.awt.Color(51, 0, 51));
        txtDeposito.setText("Monto de Movimiento");

        btnDeposito.setBackground(new java.awt.Color(204, 153, 255));
        btnDeposito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeposito.setForeground(new java.awt.Color(111, 47, 168));
        btnDeposito.setText("Realizar Depósito");
        btnDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoActionPerformed(evt);
            }
        });

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        txtCuentaDestino.setBackground(new java.awt.Color(240, 240, 240));
        txtCuentaDestino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCuentaDestino.setForeground(new java.awt.Color(0, 0, 51));
        txtCuentaDestino.setText("Cuenta Destino");
        txtCuentaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaDestinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDeposito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnDeposito)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
        // Datos
    String cuenta = txtCuenta.getText();
    String montoTexto = txtDeposito.getText();
    String cuentaDestino = txtCuentaDestino.getText(); // Obtener la cuenta destino desde el campo de texto

    // Verificar que los campos no estén vacíos
    if (cuenta.isEmpty() || montoTexto.isEmpty() || (cuentaDestino.isEmpty() && jComboBox1.getSelectedItem().equals("Transferencia"))) {
        JOptionPane.showMessageDialog(rootPane, "Por favor, complete todos los campos.");
        return;
    }

    double monto = 0;
    try {
        monto = Double.parseDouble(montoTexto); // Intentar convertir el monto a double
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "Por favor, ingrese un monto válido.");
        return;
    }

    // Obtener el tipo de movimiento seleccionado desde el ComboBox
    String tipoDescripcion = (String) jComboBox1.getSelectedItem();
    String tipoCodigo = movimientoCodigos.get(tipoDescripcion);

    // Asegurarse de que tipoCodigo no sea nulo
    if (tipoCodigo == null) {
        JOptionPane.showMessageDialog(rootPane, "Por favor, seleccione un tipo de movimiento válido.");
        return;
    }

    // Proceso
    EurekaControlador control = new EurekaControlador();

    if (tipoCodigo.equals("004")) { // Retiro
        int estado = control.regRetiro(cuenta, monto, tipoCodigo);
        if (estado == -2) {
            JOptionPane.showMessageDialog(rootPane, "Saldo insuficiente.");
        } else if (estado == -1) {
            JOptionPane.showMessageDialog(rootPane, "Error en el proceso de retiro.");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Retiro realizado satisfactoriamente.");
        }
    } else if (tipoCodigo.equals("009")) { // Transferencia
        // Registrar la salida en la cuenta origen
        int estado = control.regRetiro(cuenta, monto, "009");
        if (estado == -2) {
            JOptionPane.showMessageDialog(rootPane, "Saldo insuficiente en la cuenta origen.");
            return;
        }
        // Registrar el ingreso en la cuenta destino
        estado = control.regDeposito(cuentaDestino, monto, "008");
        if (estado == -1) {
            JOptionPane.showMessageDialog(rootPane, "Error en el depósito en la cuenta destino.");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Transferencia realizada satisfactoriamente.");
        }
    } else { // Depósito
        int estado = control.regDeposito(cuenta, monto, tipoCodigo);
        if (estado == -1) {
            JOptionPane.showMessageDialog(rootPane, "Error en el proceso, revise sus datos.");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Depósito realizado satisfactoriamente.");
        }
    }
    }//GEN-LAST:event_btnDepositoActionPerformed

    private void txtCuentaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaDestinoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepositosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepositosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepositosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepositosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepositosVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposito;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtCuentaDestino;
    private javax.swing.JTextField txtDeposito;
    // End of variables declaration//GEN-END:variables
}
