//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajecitos_Desktop.ViajecitosReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDTO", Namespace="http://schemas.datacontract.org/2004/07/CONDOR_Servidor.DTO")]
    [System.SerializableAttribute()]
    public partial class UsuarioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VueloDTO", Namespace="http://schemas.datacontract.org/2004/07/CONDOR_Servidor.DTO")]
    [System.SerializableAttribute()]
    public partial class VueloDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CuposDisponiblesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HoraSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CiudadDestino {
            get {
                return this.CiudadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadDestinoField, value) != true)) {
                    this.CiudadDestinoField = value;
                    this.RaisePropertyChanged("CiudadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CiudadOrigen {
            get {
                return this.CiudadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadOrigenField, value) != true)) {
                    this.CiudadOrigenField = value;
                    this.RaisePropertyChanged("CiudadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CuposDisponibles {
            get {
                return this.CuposDisponiblesField;
            }
            set {
                if ((this.CuposDisponiblesField.Equals(value) != true)) {
                    this.CuposDisponiblesField = value;
                    this.RaisePropertyChanged("CuposDisponibles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HoraSalida {
            get {
                return this.HoraSalidaField;
            }
            set {
                if ((this.HoraSalidaField.Equals(value) != true)) {
                    this.HoraSalidaField = value;
                    this.RaisePropertyChanged("HoraSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompraDetalleDTO", Namespace="http://schemas.datacontract.org/2004/07/CONDOR_Servidor.DTO")]
    [System.SerializableAttribute()]
    public partial class CompraDetalleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HoraSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CiudadDestino {
            get {
                return this.CiudadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadDestinoField, value) != true)) {
                    this.CiudadDestinoField = value;
                    this.RaisePropertyChanged("CiudadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CiudadOrigen {
            get {
                return this.CiudadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadOrigenField, value) != true)) {
                    this.CiudadOrigenField = value;
                    this.RaisePropertyChanged("CiudadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCompra {
            get {
                return this.FechaCompraField;
            }
            set {
                if ((this.FechaCompraField.Equals(value) != true)) {
                    this.FechaCompraField = value;
                    this.RaisePropertyChanged("FechaCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HoraSalida {
            get {
                return this.HoraSalidaField;
            }
            set {
                if ((this.HoraSalidaField.Equals(value) != true)) {
                    this.HoraSalidaField = value;
                    this.RaisePropertyChanged("HoraSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCompra {
            get {
                return this.IdCompraField;
            }
            set {
                if ((this.IdCompraField.Equals(value) != true)) {
                    this.IdCompraField = value;
                    this.RaisePropertyChanged("IdCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CiudadDTO", Namespace="http://schemas.datacontract.org/2004/07/CONDOR_Servidor.DTO")]
    [System.SerializableAttribute()]
    public partial class CiudadDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCiudadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCiudad {
            get {
                return this.NombreCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCiudadField, value) != true)) {
                    this.NombreCiudadField = value;
                    this.RaisePropertyChanged("NombreCiudad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaDTO", Namespace="http://schemas.datacontract.org/2004/07/CONDOR_Servidor.DTO")]
    [System.SerializableAttribute()]
    public partial class FacturaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IVAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroBoletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SubtotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalAPagarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorUnitarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CiudadDestino {
            get {
                return this.CiudadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadDestinoField, value) != true)) {
                    this.CiudadDestinoField = value;
                    this.RaisePropertyChanged("CiudadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CiudadOrigen {
            get {
                return this.CiudadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadOrigenField, value) != true)) {
                    this.CiudadOrigenField = value;
                    this.RaisePropertyChanged("CiudadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFactura {
            get {
                return this.FechaFacturaField;
            }
            set {
                if ((this.FechaFacturaField.Equals(value) != true)) {
                    this.FechaFacturaField = value;
                    this.RaisePropertyChanged("FechaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IVA {
            get {
                return this.IVAField;
            }
            set {
                if ((this.IVAField.Equals(value) != true)) {
                    this.IVAField = value;
                    this.RaisePropertyChanged("IVA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCompra {
            get {
                return this.IdCompraField;
            }
            set {
                if ((this.IdCompraField.Equals(value) != true)) {
                    this.IdCompraField = value;
                    this.RaisePropertyChanged("IdCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFactura {
            get {
                return this.IdFacturaField;
            }
            set {
                if ((this.IdFacturaField.Equals(value) != true)) {
                    this.IdFacturaField = value;
                    this.RaisePropertyChanged("IdFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComprador {
            get {
                return this.NombreCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompradorField, value) != true)) {
                    this.NombreCompradorField = value;
                    this.RaisePropertyChanged("NombreComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroBoleto {
            get {
                return this.NumeroBoletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroBoletoField, value) != true)) {
                    this.NumeroBoletoField = value;
                    this.RaisePropertyChanged("NumeroBoleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Subtotal {
            get {
                return this.SubtotalField;
            }
            set {
                if ((this.SubtotalField.Equals(value) != true)) {
                    this.SubtotalField = value;
                    this.RaisePropertyChanged("Subtotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAPagar {
            get {
                return this.TotalAPagarField;
            }
            set {
                if ((this.TotalAPagarField.Equals(value) != true)) {
                    this.TotalAPagarField = value;
                    this.RaisePropertyChanged("TotalAPagar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorUnitario {
            get {
                return this.ValorUnitarioField;
            }
            set {
                if ((this.ValorUnitarioField.Equals(value) != true)) {
                    this.ValorUnitarioField = value;
                    this.RaisePropertyChanged("ValorUnitario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ViajecitosReference.IViajecitosService")]
    public interface IViajecitosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/Login", ReplyAction="http://tempuri.org/IViajecitosService/LoginResponse")]
        Viajecitos_Desktop.ViajecitosReference.UsuarioDTO Login(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/Login", ReplyAction="http://tempuri.org/IViajecitosService/LoginResponse")]
        System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.UsuarioDTO> LoginAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/BuscarVueloMayorValor", ReplyAction="http://tempuri.org/IViajecitosService/BuscarVueloMayorValorResponse")]
        Viajecitos_Desktop.ViajecitosReference.VueloDTO BuscarVueloMayorValor(string origen, string destino, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/BuscarVueloMayorValor", ReplyAction="http://tempuri.org/IViajecitosService/BuscarVueloMayorValorResponse")]
        System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.VueloDTO> BuscarVueloMayorValorAsync(string origen, string destino, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/RegistrarCompra", ReplyAction="http://tempuri.org/IViajecitosService/RegistrarCompraResponse")]
        string RegistrarCompra(int idVuelo, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/RegistrarCompra", ReplyAction="http://tempuri.org/IViajecitosService/RegistrarCompraResponse")]
        System.Threading.Tasks.Task<string> RegistrarCompraAsync(int idVuelo, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/ObtenerUsuarioPorId", ReplyAction="http://tempuri.org/IViajecitosService/ObtenerUsuarioPorIdResponse")]
        Viajecitos_Desktop.ViajecitosReference.UsuarioDTO ObtenerUsuarioPorId(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/ObtenerUsuarioPorId", ReplyAction="http://tempuri.org/IViajecitosService/ObtenerUsuarioPorIdResponse")]
        System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.UsuarioDTO> ObtenerUsuarioPorIdAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/RegistrarUsuario", ReplyAction="http://tempuri.org/IViajecitosService/RegistrarUsuarioResponse")]
        string RegistrarUsuario(string usuario, string password, string nombre, string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/RegistrarUsuario", ReplyAction="http://tempuri.org/IViajecitosService/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<string> RegistrarUsuarioAsync(string usuario, string password, string nombre, string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/ObtenerTodasLasCompras", ReplyAction="http://tempuri.org/IViajecitosService/ObtenerTodasLasComprasResponse")]
        Viajecitos_Desktop.ViajecitosReference.CompraDetalleDTO[] ObtenerTodasLasCompras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/ObtenerTodasLasCompras", ReplyAction="http://tempuri.org/IViajecitosService/ObtenerTodasLasComprasResponse")]
        System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.CompraDetalleDTO[]> ObtenerTodasLasComprasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/ListarVuelos", ReplyAction="http://tempuri.org/IViajecitosService/ListarVuelosResponse")]
        Viajecitos_Desktop.ViajecitosReference.VueloDTO[] ListarVuelos(string origen, string destino, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/ListarVuelos", ReplyAction="http://tempuri.org/IViajecitosService/ListarVuelosResponse")]
        System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.VueloDTO[]> ListarVuelosAsync(string origen, string destino, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/ListarCiudades", ReplyAction="http://tempuri.org/IViajecitosService/ListarCiudadesResponse")]
        Viajecitos_Desktop.ViajecitosReference.CiudadDTO[] ListarCiudades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/ListarCiudades", ReplyAction="http://tempuri.org/IViajecitosService/ListarCiudadesResponse")]
        System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.CiudadDTO[]> ListarCiudadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/ObtenerComprasPorUsuario", ReplyAction="http://tempuri.org/IViajecitosService/ObtenerComprasPorUsuarioResponse")]
        Viajecitos_Desktop.ViajecitosReference.CompraDetalleDTO[] ObtenerComprasPorUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/ObtenerComprasPorUsuario", ReplyAction="http://tempuri.org/IViajecitosService/ObtenerComprasPorUsuarioResponse")]
        System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.CompraDetalleDTO[]> ObtenerComprasPorUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/RegistrarCompraConFactura", ReplyAction="http://tempuri.org/IViajecitosService/RegistrarCompraConFacturaResponse")]
        Viajecitos_Desktop.ViajecitosReference.FacturaDTO RegistrarCompraConFactura(int idVuelo, int idUsuario, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/RegistrarCompraConFactura", ReplyAction="http://tempuri.org/IViajecitosService/RegistrarCompraConFacturaResponse")]
        System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.FacturaDTO> RegistrarCompraConFacturaAsync(int idVuelo, int idUsuario, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/ObtenerFacturasPorUsuario", ReplyAction="http://tempuri.org/IViajecitosService/ObtenerFacturasPorUsuarioResponse")]
        Viajecitos_Desktop.ViajecitosReference.FacturaDTO[] ObtenerFacturasPorUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViajecitosService/ObtenerFacturasPorUsuario", ReplyAction="http://tempuri.org/IViajecitosService/ObtenerFacturasPorUsuarioResponse")]
        System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.FacturaDTO[]> ObtenerFacturasPorUsuarioAsync(int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IViajecitosServiceChannel : Viajecitos_Desktop.ViajecitosReference.IViajecitosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViajecitosServiceClient : System.ServiceModel.ClientBase<Viajecitos_Desktop.ViajecitosReference.IViajecitosService>, Viajecitos_Desktop.ViajecitosReference.IViajecitosService {
        
        public ViajecitosServiceClient() {
        }
        
        public ViajecitosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViajecitosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViajecitosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViajecitosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Viajecitos_Desktop.ViajecitosReference.UsuarioDTO Login(string usuario, string password) {
            return base.Channel.Login(usuario, password);
        }
        
        public System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.UsuarioDTO> LoginAsync(string usuario, string password) {
            return base.Channel.LoginAsync(usuario, password);
        }
        
        public Viajecitos_Desktop.ViajecitosReference.VueloDTO BuscarVueloMayorValor(string origen, string destino, System.DateTime fecha) {
            return base.Channel.BuscarVueloMayorValor(origen, destino, fecha);
        }
        
        public System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.VueloDTO> BuscarVueloMayorValorAsync(string origen, string destino, System.DateTime fecha) {
            return base.Channel.BuscarVueloMayorValorAsync(origen, destino, fecha);
        }
        
        public string RegistrarCompra(int idVuelo, int idUsuario) {
            return base.Channel.RegistrarCompra(idVuelo, idUsuario);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarCompraAsync(int idVuelo, int idUsuario) {
            return base.Channel.RegistrarCompraAsync(idVuelo, idUsuario);
        }
        
        public Viajecitos_Desktop.ViajecitosReference.UsuarioDTO ObtenerUsuarioPorId(int idUsuario) {
            return base.Channel.ObtenerUsuarioPorId(idUsuario);
        }
        
        public System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.UsuarioDTO> ObtenerUsuarioPorIdAsync(int idUsuario) {
            return base.Channel.ObtenerUsuarioPorIdAsync(idUsuario);
        }
        
        public string RegistrarUsuario(string usuario, string password, string nombre, string apellido) {
            return base.Channel.RegistrarUsuario(usuario, password, nombre, apellido);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarUsuarioAsync(string usuario, string password, string nombre, string apellido) {
            return base.Channel.RegistrarUsuarioAsync(usuario, password, nombre, apellido);
        }
        
        public Viajecitos_Desktop.ViajecitosReference.CompraDetalleDTO[] ObtenerTodasLasCompras() {
            return base.Channel.ObtenerTodasLasCompras();
        }
        
        public System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.CompraDetalleDTO[]> ObtenerTodasLasComprasAsync() {
            return base.Channel.ObtenerTodasLasComprasAsync();
        }
        
        public Viajecitos_Desktop.ViajecitosReference.VueloDTO[] ListarVuelos(string origen, string destino, System.DateTime fecha) {
            return base.Channel.ListarVuelos(origen, destino, fecha);
        }
        
        public System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.VueloDTO[]> ListarVuelosAsync(string origen, string destino, System.DateTime fecha) {
            return base.Channel.ListarVuelosAsync(origen, destino, fecha);
        }
        
        public Viajecitos_Desktop.ViajecitosReference.CiudadDTO[] ListarCiudades() {
            return base.Channel.ListarCiudades();
        }
        
        public System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.CiudadDTO[]> ListarCiudadesAsync() {
            return base.Channel.ListarCiudadesAsync();
        }
        
        public Viajecitos_Desktop.ViajecitosReference.CompraDetalleDTO[] ObtenerComprasPorUsuario(int idUsuario) {
            return base.Channel.ObtenerComprasPorUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.CompraDetalleDTO[]> ObtenerComprasPorUsuarioAsync(int idUsuario) {
            return base.Channel.ObtenerComprasPorUsuarioAsync(idUsuario);
        }
        
        public Viajecitos_Desktop.ViajecitosReference.FacturaDTO RegistrarCompraConFactura(int idVuelo, int idUsuario, int cantidad) {
            return base.Channel.RegistrarCompraConFactura(idVuelo, idUsuario, cantidad);
        }
        
        public System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.FacturaDTO> RegistrarCompraConFacturaAsync(int idVuelo, int idUsuario, int cantidad) {
            return base.Channel.RegistrarCompraConFacturaAsync(idVuelo, idUsuario, cantidad);
        }
        
        public Viajecitos_Desktop.ViajecitosReference.FacturaDTO[] ObtenerFacturasPorUsuario(int idUsuario) {
            return base.Channel.ObtenerFacturasPorUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<Viajecitos_Desktop.ViajecitosReference.FacturaDTO[]> ObtenerFacturasPorUsuarioAsync(int idUsuario) {
            return base.Channel.ObtenerFacturasPorUsuarioAsync(idUsuario);
        }
    }
}
